# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/todo
    username: root
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
